ApexIelts/Areas/OfficialAdmin/Controllers/AchieversController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AdminPaneNew.Areas.OfficialAdmin.Models;
using onlineportal.Areas.AdminPanel.Models;

namespace AdminPaneNew.Areas.OfficialAdmin.Controllers
{
    public class AchieversController : Controller
    {
        private dbcontext db = new dbcontext();
        public static string img;
        // GET: OfficialAdmin/Achievers
        public ActionResult Index()
        {
            return View(db.Achievers.ToList());
        }

        // GET: OfficialAdmin/Achievers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Achievers achievers = db.Achievers.Find(id);
            if (achievers == null)
            {
                return HttpNotFound();
            }
            return View(achievers);
        }

        // GET: OfficialAdmin/Achievers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: OfficialAdmin/Achievers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Achieverid,Name,ShortDescription,Image,Course,date,Reading,Writing,Listening,Speaking,Overall")] Achievers achievers, HttpPostedFileBase file, Helper Help)
        {
            if (ModelState.IsValid)
            {
                achievers.date = System.DateTime.Now;
                achievers.Image = Help.uploadfile(file);
                db.Achievers.Add(achievers);
                db.SaveChanges();
                TempData["Success"] = "Saved Successfully";
                return RedirectToAction("Index");
            }

            return View(achievers);
        }

        // GET: OfficialAdmin/Achievers/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Achievers achievers = db.Achievers.Find(id);
            img = achievers.Image;
            if (achievers == null)
            {
                return HttpNotFound();
            }
            return View(achievers);
        }

        // POST: OfficialAdmin/Achievers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Achieverid,Name,ShortDescription,Image,Course,date,Reading,Writing,Listening,Speaking,Overall")] Achievers achievers, HttpPostedFileBase file, Helper Help)
        {
            if (ModelState.IsValid)
            {
                achievers.date = System.DateTime.Now;
                achievers.Image = file != null ? Help.uploadfile(file) : img;
                #region delete file
                string fullPath = Request.MapPath("~/UploadedFiles/" + img);
                if (img == achievers.Image)
                {
                }
                else
                {
                    if (System.IO.File.Exists(fullPath))
                    {
                        System.IO.File.Delete(fullPath);
                    }
                }
                #endregion
                db.Entry(achievers).State = EntityState.Modified;
                db.SaveChanges();
                TempData["Success"] = "Updated Successfully";
                return RedirectToAction("Index");
            }
            return View(achievers);
        }

        // GET: OfficialAdmin/Achievers/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Achievers achievers = db.Achievers.Find(id);
            if (achievers == null)
            {
                return HttpNotFound();
            }
            return View(achievers);
        }

        // POST: OfficialAdmin/Achievers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Achievers achievers = db.Achievers.Find(id);
            db.Achievers.Remove(achievers);
            db.SaveChanges();
            TempData["Success"] = "Deleted Successfully";
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ApexIelts/Areas/OfficialAdmin/Views/Achievers/Create.cshtml
@model AdminPaneNew.Areas.OfficialAdmin.Models.Achievers

@{
  ViewBag.Title = "Create";

   
   Layout = "~/Areas/OfficialAdmin/Views/Shared/Layout.cshtml";
}
@section Pagename {

    Achievers

}

@using (Html.BeginForm("Create", "Achievers", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h3>Create</h3>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShortDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ShortDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ShortDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input id="file" type="file" title="search image" class="form-control" name="file" />
                @Html.Label("460px X 290px", htmlAttributes: new { @class = "control-label" })
                @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Course, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Course, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Course, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Reading, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Reading, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Reading, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Writing, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Writing, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Writing, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Listening, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Listening, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Listening, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Speaking, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Speaking, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Speaking, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Overall, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Overall, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Overall, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-danger" />
 		@Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-danger" })

            </div>
        </div>
    </div>
    <div class="preview_box">
        <img id="preview_img" src="" />
    </div>
    <div id="image-holder"> </div>
}

<div>
   
</div>

ApexIelts/Areas/OfficialAdmin/Views/Achievers/Delete.cshtml
@model AdminPaneNew.Areas.OfficialAdmin.Models.Achievers

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/OfficialAdmin/Views/Shared/Layout.cshtml";
}
@section Pagename {

    Achievers

}

<h3>Are you sure you want to delete this?</h3>
<div>
    <h3>Delete</h3>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ShortDescription)
        </dt>

        <dd>
            @Html.Raw(Model.ShortDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            <img src="~/UploadedFiles/@Model.Image" style="width:100px;" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Course)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Course)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Reading)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Reading)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Writing)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Writing)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Listening)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Listening)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Speaking)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Speaking)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Overall)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Overall)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
	    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-danger" })
        </div>
    }
</div>

ApexIelts/Areas/OfficialAdmin/Views/Achievers/Details.cshtml
@model AdminPaneNew.Areas.OfficialAdmin.Models.Achievers

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/OfficialAdmin/Views/Shared/Layout.cshtml";
}
@section Pagename {

    Achievers

}

<div>
    <h3>Details</h3>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ShortDescription)
        </dt>

        <dd>
            @Html.Raw(Model.ShortDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            <img src="~/UploadedFiles/@Model.Image" style="width:100px;" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Course)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Course)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Reading)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Reading)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Writing)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Writing)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Listening)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Listening)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Speaking)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Speaking)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Overall)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Overall)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Achieverid }) |
     @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-danger" })
</p>

ApexIelts/Areas/OfficialAdmin/Views/Achievers/Edit.cshtml
@model AdminPaneNew.Areas.OfficialAdmin.Models.Achievers

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/OfficialAdmin/Views/Shared/Layout.cshtml";
}
@section Pagename {

    Achievers

}
@using (Html.BeginForm("Edit", "Achievers", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h3>Edit</h3>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Achieverid)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShortDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ShortDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ShortDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                <input id="file" type="file" title="search image" class="form-control" name="file" />
                @Html.Label("250px X 200px", htmlAttributes: new { @class = "control-label" })
                @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
            </div>
            <div class="col-md-4">
                <img src="~/UploadedFiles/@Model.Image" alt="" style="width:150px;" class="img-responsive" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Course, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Course, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Course, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Reading, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Reading, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Reading, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Writing, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Writing, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Writing, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Listening, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Listening, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Listening, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Speaking, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Speaking, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Speaking, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Overall, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Overall, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Overall, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-danger" />
 	       @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
}
<div class="preview_box">
    <img id="preview_img" src="" />
</div>
<div id="image-holder"> </div>
<div>

</div>

ApexIelts/Areas/OfficialAdmin/Views/Achievers/Index.cshtml
@model IEnumerable<AdminPaneNew.Areas.OfficialAdmin.Models.Achievers>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/OfficialAdmin/Views/Shared/Layout.cshtml";
}
@section Pagename {

    Achievers

}
<h2><b>Index</b></h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<div class="table-responsive">
    <table class="table table-striped table-bordered table-hover" id="dataTables-example">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Image)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Course)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Reading)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Writing)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Listening)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Speaking)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Overall)
                </th>
                <th>Action</th>
            </tr>
            </thead>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        <img src="~/UploadedFiles/@item.Image" width="100" />
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Course)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Reading)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Writing)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Listening)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Speaking)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Overall)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.Achieverid }) |
                        @Html.ActionLink("Details", "Details", new { id = item.Achieverid }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.Achieverid })
                    </td>
                </tr>
            }

    </table>
    </div>