ApexIelts/Areas/OfficialAdmin/Controllers/ClientlogoesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AdminPaneNew.Areas.OfficialAdmin.Models;
using onlineportal.Areas.AdminPanel.Models;

namespace AdminPaneNew.Areas.OfficialAdmin.Controllers
{
    public class ClientlogoesController : Controller
    {
        private dbcontext db = new dbcontext();
        public static string img;
        // GET: OfficialAdmin/Clientlogoes
        public ActionResult Index()
        {
            return View(db.Clientlogoes.ToList());
        }

        // GET: OfficialAdmin/Clientlogoes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Clientlogo clientlogo = db.Clientlogoes.Find(id);
            if (clientlogo == null)
            {
                return HttpNotFound();
            }
            return View(clientlogo);
        }

        // GET: OfficialAdmin/Clientlogoes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: OfficialAdmin/Clientlogoes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Clientid,Name,Image,date")] Clientlogo clientlogo, HttpPostedFileBase file, Helper Help)
        {
            if (ModelState.IsValid)
            {
                clientlogo.date = System.DateTime.Now;
                clientlogo.Image = Help.uploadfile(file);
                db.Clientlogoes.Add(clientlogo);
                db.SaveChanges();
                TempData["Success"] = "Saved Successfully";
                return RedirectToAction("Index");
            }

            return View(clientlogo);
        }

        // GET: OfficialAdmin/Clientlogoes/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Clientlogo clientlogo = db.Clientlogoes.Find(id);
            img = clientlogo.Image;
            if (clientlogo == null)
            {
                return HttpNotFound();
            }
            return View(clientlogo);
        }

        // POST: OfficialAdmin/Clientlogoes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Clientid,Name,Image,date")] Clientlogo clientlogo, HttpPostedFileBase file, Helper Help)
        {
            if (ModelState.IsValid)
            {
                clientlogo.date = System.DateTime.Now;
                clientlogo.Image = file != null ? Help.uploadfile(file) : img;
                #region delete file
                string fullPath = Request.MapPath("~/UploadedFiles/" + img);
                if (img == clientlogo.Image)
                {
                }
                else
                {
                    if (System.IO.File.Exists(fullPath))
                    {
                        System.IO.File.Delete(fullPath);
                    }
                }
                #endregion
                db.Entry(clientlogo).State = EntityState.Modified;
                db.SaveChanges();
                TempData["Success"] = "Updated Successfully";
                return RedirectToAction("Index");
            }
            return View(clientlogo);
        }

        // GET: OfficialAdmin/Clientlogoes/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Clientlogo clientlogo = db.Clientlogoes.Find(id);
            if (clientlogo == null)
            {
                return HttpNotFound();
            }
            return View(clientlogo);
        }

        // POST: OfficialAdmin/Clientlogoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Clientlogo clientlogo = db.Clientlogoes.Find(id);
            db.Clientlogoes.Remove(clientlogo);
            db.SaveChanges();
            TempData["Success"] = "Deleted Successfully";
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ApexIelts/Areas/OfficialAdmin/Views/Clientlogoes/Create.cshtml
@model AdminPaneNew.Areas.OfficialAdmin.Models.Clientlogo

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/OfficialAdmin/Views/Shared/Layout.cshtml";
}

@section Pagename {

    Clientlogo

}

@using (Html.BeginForm("Create", "Clientlogoes", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h3>Create</h3>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input id="file" type="file" title="search image" class="form-control" name="file" />
                @Html.Label("170px X 110px", htmlAttributes: new { @class = "control-label" })
                @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
            </div>
        </div>
       
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-danger" />
                @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
}

<div>
</div>

ApexIelts/Areas/OfficialAdmin/Views/Clientlogoes/Delete.cshtml
@model AdminPaneNew.Areas.OfficialAdmin.Models.Clientlogo

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/OfficialAdmin/Views/Shared/Layout.cshtml";
}
@section Pagename {

    Clientlogo

}

<h3>Are you sure you want to delete this?</h3>
<div>
    <h3>Delete</h3>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            <img src="~/UploadedFiles/@Model.Image" style="width:100px;" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.date)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-danger" })
        </div>
    }
</div>

ApexIelts/Areas/OfficialAdmin/Views/Clientlogoes/Details.cshtml
@model AdminPaneNew.Areas.OfficialAdmin.Models.Clientlogo

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/OfficialAdmin/Views/Shared/Layout.cshtml";
}
@section Pagename {

    Clientlogo

}

<div>
    <h3>Details</h3>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            <img src="~/UploadedFiles/@Model.Image" style="width:100px;" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.date)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Clientid },new { @class = "btn btn-danger"}) 
    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-danger" })
</p>

ApexIelts/Areas/OfficialAdmin/Views/Clientlogoes/Edit.cshtml
@model AdminPaneNew.Areas.OfficialAdmin.Models.Clientlogo

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/OfficialAdmin/Views/Shared/Layout.cshtml";
}

@section Pagename {

    Clientlogo

}

@using (Html.BeginForm("Edit", "Clientlogoes", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h3>Edit</h3>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Clientid)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                <input id="file" type="file" title="search image" class="form-control" name="file" />
                @Html.Label("170px X 110px", htmlAttributes: new { @class = "control-label" })
                @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
            </div>
            <div class="col-md-4">
                <img src="~/UploadedFiles/@Model.Image" alt="" style="width:150px;" class="img-responsive" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-danger" />
                @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-danger" })
            </div>
        </div>
       
    </div>
}

<div>
</div>

ApexIelts/Areas/OfficialAdmin/Views/Clientlogoes/Index.cshtml
@model IEnumerable<AdminPaneNew.Areas.OfficialAdmin.Models.Clientlogo>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/OfficialAdmin/Views/Shared/Layout.cshtml";
}
@section Pagename {

    Clientlogo

}
<h2><b>Index</b></h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<div class="table-responsive">
    <table class="table table-striped table-bordered table-hover" id="dataTables-example">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Image)
                </th>
                @*<th>
                    @Html.DisplayNameFor(model => model.date)
                </th>*@
                <th>Action</th>
            </tr>
            </thead>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        <img src="~/UploadedFiles/@item.Image" width="100" />
                    </td>
                    @*<td>
                        @Html.DisplayFor(modelItem => item.date)
                    </td>*@
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.Clientid }) |
                        @Html.ActionLink("Details", "Details", new { id = item.Clientid }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.Clientid })
                    </td>
                </tr>
            }

</table>
    </div>