ApexIelts/Areas/OfficialAdmin/Controllers/FeaturesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AdminPaneNew.Areas.OfficialAdmin.Models;
using onlineportal.Areas.AdminPanel.Models;

namespace AdminPaneNew.Areas.OfficialAdmin.Controllers
{
    public class FeaturesController : Controller
    {
        private dbcontext db = new dbcontext();
        public static string img, thumb;
        // GET: OfficialAdmin/Features
        public ActionResult Index()
        {
            return View(db.Features.ToList());
        }

        // GET: OfficialAdmin/Features/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Features features = db.Features.Find(id);
            if (features == null)
            {
                return HttpNotFound();
            }
            return View(features);
        }

        // GET: OfficialAdmin/Features/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: OfficialAdmin/Features/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Featureid,Name,Description,ShortDescription,Image,date,Thumbnail,Keyword,MetaDescription")] Features features, HttpPostedFileBase file, Helper Help)
        {
            if (ModelState.IsValid)
            {
                features.date = System.DateTime.Now;
                features.Image = Help.uploadfile(file);
                features.Thumbnail = Help.uploadfile(file);
                db.Features.Add(features);
                db.SaveChanges();
                TempData["Success"] = "Saved Successfully";
                return RedirectToAction("Index");
            }

            return View(features);
        }

        // GET: OfficialAdmin/Features/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Features features = db.Features.Find(id);
            img = features.Image;
            thumb = features.Thumbnail;
            if (features == null)
            {
                return HttpNotFound();
            }
            return View(features);
        }

        // POST: OfficialAdmin/Features/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Featureid,Name,Description,ShortDescription,Image,date,Thumbnail,Keyword,MetaDescription")] Features features, HttpPostedFileBase file, Helper Help)
        {
            if (ModelState.IsValid)
            {
                features.date = System.DateTime.Now;
                features.Image = file != null ? Help.uploadfile(file) : img;
                #region delete file
                string fullPath = Request.MapPath("~/UploadedFiles/" + img);
                if (img == features.Image)
                {
                }
                else
                {
                    if (System.IO.File.Exists(fullPath))
                    {
                        System.IO.File.Delete(fullPath);
                    }
                }
                #endregion
                features.Thumbnail = file != null ? Help.uploadfile(file) : thumb;
                #region delete file
                string fullPath2 = Request.MapPath("~/UploadedFiles/" + thumb);
                if (thumb == features.Thumbnail)
                {
                }
                else
                {
                    if (System.IO.File.Exists(fullPath2))
                    {
                        System.IO.File.Delete(fullPath2);
                    }
                }
                #endregion
                db.Entry(features).State = EntityState.Modified;
                db.SaveChanges();
                TempData["Success"] = "Updated Successfully";
                return RedirectToAction("Index");
            }
            return View(features);
        }

        // GET: OfficialAdmin/Features/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Features features = db.Features.Find(id);
            if (features == null)
            {
                return HttpNotFound();
            }
            return View(features);
        }

        // POST: OfficialAdmin/Features/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Features features = db.Features.Find(id);
            db.Features.Remove(features);
            db.SaveChanges();
            TempData["Success"] = "Deleted Successfully";
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ApexIelts/Areas/OfficialAdmin/Views/Features/Create.cshtml
@model AdminPaneNew.Areas.OfficialAdmin.Models.Features

@{
  ViewBag.Title = "Create";

   
   Layout = "~/Areas/OfficialAdmin/Views/Shared/Layout.cshtml";
}
@section Pagename {

    Features

}

@using (Html.BeginForm("Create", "Features", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h3>Create</h3>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShortDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.ShortDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ShortDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input id="file" type="file" title="search image" class="form-control" name="file" />
                @Html.Label("460px X 290px", htmlAttributes: new { @class = "control-label" })
                @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Thumbnail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input id="file2" type="file" title="search image" class="form-control" name="file2" />
                @Html.Label("150px X 150px", htmlAttributes: new { @class = "control-label" })
                @Html.ValidationMessageFor(model => model.Thumbnail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Keyword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Keyword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Keyword, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MetaDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MetaDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MetaDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-danger" />
 		        @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-danger" })

            </div>
        </div>
    </div>
    <div class="preview_box">
        <img id="preview_img" src="" />
    </div>
            <div id="image-holder"> </div>
}

<div>
   
</div>

ApexIelts/Areas/OfficialAdmin/Views/Features/Delete.cshtml
@model AdminPaneNew.Areas.OfficialAdmin.Models.Features

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/OfficialAdmin/Views/Shared/Layout.cshtml";
}
@section Pagename {

    Features

}

<h3>Are you sure you want to delete this?</h3>
<div>
    <h3>Delete</h3>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            
            @Html.DisplayNameFor(model => model.ShortDescription)
        </dt>

        <dd>
            @Html.Raw(Model.ShortDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            <img src="~/UploadedFiles/@Model.Image" style="width:100px;" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.date)
        </dd>


    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
	    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-danger" })
        </div>
    }
</div>

ApexIelts/Areas/OfficialAdmin/Views/Features/Details.cshtml
@model AdminPaneNew.Areas.OfficialAdmin.Models.Features

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/OfficialAdmin/Views/Shared/Layout.cshtml";
}
@section Pagename {

    Features

}

<div>
    <h3>Details</h3>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        

        <dt>
            @Html.DisplayNameFor(model => model.ShortDescription)
        </dt>

        <dd>
            @Html.Raw(Model.ShortDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            <img src="~/UploadedFiles/@Model.Image" style="width:100px;" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.date)
        </dd>
      
        <dt>
            @Html.DisplayNameFor(model => model.Keyword)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Keyword)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MetaDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MetaDescription)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Featureid }, new { @class = "btn btn-danger" }) |
    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-danger" })
</p>

ApexIelts/Areas/OfficialAdmin/Views/Features/Edit.cshtml
@model AdminPaneNew.Areas.OfficialAdmin.Models.Features

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/OfficialAdmin/Views/Shared/Layout.cshtml";
}
@section Pagename {

    Features

}
@using (Html.BeginForm("Edit", "Features", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h3>Edit</h3>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Featureid)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShortDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.ShortDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ShortDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                <input id="file" type="file" title="search image" class="form-control" name="file" />
                @Html.Label("460px X 290px", htmlAttributes: new { @class = "control-label" })
                @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
            </div>
            <div class="col-md-4">
                <img src="~/UploadedFiles/@Model.Image" alt="" style="width:150px;" class="img-responsive" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Thumbnail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                <input id="file2" type="file" title="search image" class="form-control" name="file2" />
                @Html.Label("150px X 150px", htmlAttributes: new { @class = "control-label" })
                @Html.ValidationMessageFor(model => model.Thumbnail, "", new { @class = "text-danger" })
            </div>
            <div class="col-md-4">
                <img src="~/UploadedFiles/@Model.Thumbnail" alt="" style="width:150px;" class="img-responsive" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Keyword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Keyword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Keyword, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MetaDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MetaDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MetaDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-danger" />
 	       @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-danger" })
            </div>
        </div>
      
    </div>
}
<div class="preview_box">
    <img id="preview_img" src="" />
</div>
<div id="image-holder"> </div>
<div>

</div>

ApexIelts/Areas/OfficialAdmin/Views/Features/Index.cshtml
@model IEnumerable<AdminPaneNew.Areas.OfficialAdmin.Models.Features>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/OfficialAdmin/Views/Shared/Layout.cshtml";
}
@section Pagename {

    Features

}
<h2><b>Index</b></h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<div class="table-responsive">
    <table class="table table-striped table-bordered table-hover" id="dataTables-example">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th style="width:1050px !important;">
                    @Html.DisplayNameFor(model => model.ShortDescription)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Image)
                </th>
                @*<th>
                    @Html.DisplayNameFor(model => model.date)
                </th>*@
                <th>Action</th>
            </tr>
            </thead>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        <div style="max-height: 50px;overflow: hidden;">
                            @Html.Raw(item.ShortDescription)
                        </div>
                    </td>
                    <td>
                        <img src="~/UploadedFiles/@item.Image" width="100" />
                    </td>
                    @*<td>
                        @Html.DisplayFor(modelItem => item.date)
                    </td>*@

                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.Featureid }) |
                        @Html.ActionLink("Details", "Details", new { id = item.Featureid }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.Featureid })
                    </td>
                </tr>
            }

</table>
    </div>